"""Centralized constants package."""

from utils.constants.app import APP_NAME, BRIDGE_PATH
from utils.constants.colors import DARK_ACCENT, DARK_ALT, DARK_BG, DARK_PANEL, LIGHT_TEXT, SUBDUED_TEXT
from utils.constants.formats import (
    CHALLENGE_LOOKUP_OPTIONS,
    FORMAT_OPTIONS,
    GOLDFISH,
    ZONE_TITLES,
)
from utils.constants.gameplay import FULL_MANA_SYMBOLS
from utils.constants.images import ATOMIC_DATA_URL
from utils.constants.paths import (
    ARCHETYPE_CACHE_FILE,
    ARCHETYPE_DECKS_CACHE_FILE,
    ARCHETYPE_LIST_CACHE_FILE,
    BASE_DATA_DIR,
    CACHE_DIR,
    CARD_DATA_DIR,
    CONFIG_DIR,
    CONFIG_FILE,
    CURR_DECK_FILE,
    DECK_CACHE_FILE,
    DECK_MONITOR_CACHE_FILE,
    DECK_MONITOR_CONFIG_FILE,
    DECK_SAVE_DIR,
    DECK_SELECTOR_SETTINGS_FILE,
    DECK_TEXT_CACHE_FILE,
    DECKS_DIR,
    LEADERBOARD_POSITIONS_FILE,
    LOGS_DIR,
    MTGO_ARTICLES_CACHE_FILE,
    MTGO_DECK_CACHE_FILE,
    ensure_base_dirs,
)
from utils.constants.storage import CARD_INSPECTOR_LOG, GUIDE_STORE, NOTES_STORE, OUTBOARD_STORE
from utils.constants.timing import (
    BULK_CACHE_MAX_AGE_DAYS,
    BULK_CACHE_MIN_AGE_DAYS,
    BULK_DATA_CACHE_FRESHNESS_SECONDS,
    COLLECTION_CACHE_MAX_AGE_SECONDS,
    DEFAULT_BULK_DATA_MAX_AGE_DAYS,
    METAGAME_CACHE_TTL_SECONDS,
    ONE_DAY_SECONDS,
    ONE_HOUR_SECONDS,
)

# Feature flag: disable MTGO decklist scraping until the new service is integrated.
import os

MTGO_DECKLISTS_ENABLED = os.getenv("MTGO_DECKLISTS_ENABLED", "false").lower() == "true"

DECK_SELECTOR_MANA_ICON_SIZE = int(26 * 0.7)

__all__ = [
    "APP_NAME",
    "BRIDGE_PATH",
    "DARK_ACCENT",
    "DARK_ALT",
    "DARK_BG",
    "DARK_PANEL",
    "LIGHT_TEXT",
    "SUBDUED_TEXT",
    "CHALLENGE_LOOKUP_OPTIONS",
    "FORMAT_OPTIONS",
    "GOLDFISH",
    "ZONE_TITLES",
    "FULL_MANA_SYMBOLS",
    "ATOMIC_DATA_URL",
    "BASE_DATA_DIR",
    "CACHE_DIR",
    "CARD_DATA_DIR",
    "CONFIG_DIR",
    "CONFIG_FILE",
    "CURR_DECK_FILE",
    "DECK_CACHE_FILE",
    "DECK_MONITOR_CACHE_FILE",
    "DECK_MONITOR_CONFIG_FILE",
    "DECK_SAVE_DIR",
    "DECK_SELECTOR_SETTINGS_FILE",
    "DECK_TEXT_CACHE_FILE",
    "DECKS_DIR",
    "LEADERBOARD_POSITIONS_FILE",
    "LOGS_DIR",
    "MTGO_ARTICLES_CACHE_FILE",
    "MTGO_DECK_CACHE_FILE",
    "ARCHETYPE_CACHE_FILE",
    "ARCHETYPE_LIST_CACHE_FILE",
    "ARCHETYPE_DECKS_CACHE_FILE",
    "ensure_base_dirs",
    "CARD_INSPECTOR_LOG",
    "GUIDE_STORE",
    "NOTES_STORE",
    "OUTBOARD_STORE",
    "BULK_CACHE_MAX_AGE_DAYS",
    "BULK_CACHE_MIN_AGE_DAYS",
    "BULK_DATA_CACHE_FRESHNESS_SECONDS",
    "COLLECTION_CACHE_MAX_AGE_SECONDS",
    "DEFAULT_BULK_DATA_MAX_AGE_DAYS",
    "METAGAME_CACHE_TTL_SECONDS",
    "ONE_DAY_SECONDS",
    "ONE_HOUR_SECONDS",
    "MTGO_DECKLISTS_ENABLED",
    "DECK_SELECTOR_MANA_ICON_SIZE",
]
