"""Centralized constants package."""

# Feature flag: disable MTGO decklist scraping until the new service is integrated.
import os

from utils.constants.paths import (
    BASE_DATA_DIR,
    CACHE_DIR,
    DECK_CACHE_DB_FILE,
    MTGO_METADATA_CACHE_FILE,
)
from utils.constants.radar import (
    RADAR_AVG_COPIES_ROUND_DIGITS,
    RADAR_EXPECTED_COPIES_ROUND_DIGITS,
    RADAR_INCLUSION_RATE_ROUND_DIGITS,
    RADAR_MIN_COPY_COUNT,
    RADAR_MIN_EXPECTED_COPIES_DEFAULT,
)
from utils.constants.timing import (
    METAGAME_STATS_LOOKBACK_DAYS,
    MTGO_BACKGROUND_FETCH_DAYS,
    MTGO_DECKLISTS_FETCH_RETRY_DELAYS_SECONDS,
    MTGO_DECKLISTS_REQUEST_TIMEOUT_SECONDS,
    ONE_DAY_SECONDS,
    ONE_HOUR_SECONDS,
    SQLITE_BUSY_TIMEOUT_MS,
    SQLITE_CONNECTION_TIMEOUT_SECONDS,
)
from utils.constants.videre import VIDERE_API_BASE_URL, VIDERE_REQUEST_TIMEOUT_SECONDS

MTGO_DECKLISTS_ENABLED = os.getenv("MTGO_DECKLISTS_ENABLED", "false").lower() == "true"

__all__ = [
    "BASE_DATA_DIR",
    "CACHE_DIR",
    "DECK_CACHE_DB_FILE",
    "METAGAME_STATS_LOOKBACK_DAYS",
    "MTGO_BACKGROUND_FETCH_DAYS",
    "MTGO_DECKLISTS_ENABLED",
    "MTGO_DECKLISTS_FETCH_RETRY_DELAYS_SECONDS",
    "MTGO_DECKLISTS_REQUEST_TIMEOUT_SECONDS",
    "MTGO_METADATA_CACHE_FILE",
    "ONE_DAY_SECONDS",
    "ONE_HOUR_SECONDS",
    "RADAR_AVG_COPIES_ROUND_DIGITS",
    "RADAR_EXPECTED_COPIES_ROUND_DIGITS",
    "RADAR_INCLUSION_RATE_ROUND_DIGITS",
    "RADAR_MIN_COPY_COUNT",
    "RADAR_MIN_EXPECTED_COPIES_DEFAULT",
    "SQLITE_BUSY_TIMEOUT_MS",
    "SQLITE_CONNECTION_TIMEOUT_SECONDS",
    "VIDERE_API_BASE_URL",
    "VIDERE_REQUEST_TIMEOUT_SECONDS",
]
