"""Centralized constants package."""

# Feature flag: disable MTGO decklist scraping until the new service is integrated.
import os

from utils.constants.paths import (
    ARCHETYPE_CACHE_FILE,
    ARCHETYPE_DECKS_CACHE_FILE,
    ARCHETYPE_LIST_CACHE_FILE,
    BASE_DATA_DIR,
    CACHE_DIR,
    CURR_DECK_FILE,
    DECK_CACHE_DB_FILE,
    DECK_TEXT_CACHE_FILE,
    DECKS_DIR,
    MTGO_DECK_CACHE_FILE,
    MTGO_METADATA_CACHE_FILE,
)
from utils.constants.radar import (
    RADAR_AVG_COPIES_ROUND_DIGITS,
    RADAR_EXPECTED_COPIES_ROUND_DIGITS,
    RADAR_INCLUSION_RATE_ROUND_DIGITS,
    RADAR_MIN_COPY_COUNT,
    RADAR_MIN_EXPECTED_COPIES_DEFAULT,
)
from utils.constants.search import (
    GOLDFISH_DECK_TABLE_COL_DATE,
    GOLDFISH_DECK_TABLE_COL_EVENT,
    GOLDFISH_DECK_TABLE_COL_NUMBER,
    GOLDFISH_DECK_TABLE_COL_PLAYER,
    GOLDFISH_DECK_TABLE_COL_RESULT,
)
from utils.constants.timing import (
    METAGAME_CACHE_TTL_SECONDS,
    MTGGOLDFISH_REQUEST_TIMEOUT_SECONDS,
    MTGGOLDFISH_STALE_CACHE_DAYS,
    MTGGOLDFISH_STALE_CACHE_SECONDS,
    MTGGOLDFISH_STATS_LOOKBACK_DAYS,
    MTGO_BACKGROUND_FETCH_DAYS,
    MTGO_BACKGROUND_FETCH_DELAY_SECONDS,
    MTGO_DECKLISTS_FETCH_RETRY_DELAYS_SECONDS,
    MTGO_DECKLISTS_REQUEST_TIMEOUT_SECONDS,
    ONE_DAY_SECONDS,
    ONE_HOUR_SECONDS,
    SQLITE_BUSY_TIMEOUT_MS,
    SQLITE_CONNECTION_TIMEOUT_SECONDS,
)
from utils.constants.videre import VIDERE_API_BASE_URL, VIDERE_REQUEST_TIMEOUT_SECONDS

MTGO_DECKLISTS_ENABLED = os.getenv("MTGO_DECKLISTS_ENABLED", "false").lower() == "true"

__all__ = [
    "ARCHETYPE_CACHE_FILE",
    "ARCHETYPE_DECKS_CACHE_FILE",
    "ARCHETYPE_LIST_CACHE_FILE",
    "BASE_DATA_DIR",
    "CACHE_DIR",
    "CURR_DECK_FILE",
    "DECK_CACHE_DB_FILE",
    "DECK_TEXT_CACHE_FILE",
    "DECKS_DIR",
    "GOLDFISH_DECK_TABLE_COL_DATE",
    "GOLDFISH_DECK_TABLE_COL_EVENT",
    "GOLDFISH_DECK_TABLE_COL_NUMBER",
    "GOLDFISH_DECK_TABLE_COL_PLAYER",
    "GOLDFISH_DECK_TABLE_COL_RESULT",
    "METAGAME_CACHE_TTL_SECONDS",
    "MTGGOLDFISH_REQUEST_TIMEOUT_SECONDS",
    "MTGGOLDFISH_STALE_CACHE_DAYS",
    "MTGGOLDFISH_STALE_CACHE_SECONDS",
    "MTGGOLDFISH_STATS_LOOKBACK_DAYS",
    "MTGO_BACKGROUND_FETCH_DAYS",
    "MTGO_BACKGROUND_FETCH_DELAY_SECONDS",
    "MTGO_DECKLISTS_ENABLED",
    "MTGO_DECKLISTS_FETCH_RETRY_DELAYS_SECONDS",
    "MTGO_DECKLISTS_REQUEST_TIMEOUT_SECONDS",
    "MTGO_DECK_CACHE_FILE",
    "MTGO_METADATA_CACHE_FILE",
    "ONE_DAY_SECONDS",
    "ONE_HOUR_SECONDS",
    "RADAR_AVG_COPIES_ROUND_DIGITS",
    "RADAR_EXPECTED_COPIES_ROUND_DIGITS",
    "RADAR_INCLUSION_RATE_ROUND_DIGITS",
    "RADAR_MIN_COPY_COUNT",
    "RADAR_MIN_EXPECTED_COPIES_DEFAULT",
    "SQLITE_BUSY_TIMEOUT_MS",
    "SQLITE_CONNECTION_TIMEOUT_SECONDS",
    "VIDERE_API_BASE_URL",
    "VIDERE_REQUEST_TIMEOUT_SECONDS",
]
