"""Radar analysis defaults."""

RADAR_AVG_COPIES_ROUND_DIGITS = 2
RADAR_INCLUSION_RATE_ROUND_DIGITS = 1
RADAR_EXPECTED_COPIES_ROUND_DIGITS = 2
RADAR_MIN_EXPECTED_COPIES_DEFAULT = 0.0
RADAR_MIN_COPY_COUNT = 1
