"""Time constants and cache aging defaults."""

ONE_HOUR_SECONDS = 60 * 60
ONE_DAY_SECONDS = 24 * 60 * 60

# Collection inventory refresh settings
COLLECTION_CACHE_MAX_AGE_SECONDS = ONE_HOUR_SECONDS

# Metagame scraping cache TTL
METAGAME_CACHE_TTL_SECONDS = ONE_HOUR_SECONDS

# Card image bulk data refresh thresholds
DEFAULT_BULK_DATA_MAX_AGE_DAYS = 30
BULK_DATA_CACHE_FRESHNESS_SECONDS = DEFAULT_BULK_DATA_MAX_AGE_DAYS * ONE_DAY_SECONDS

BULK_CACHE_MIN_AGE_DAYS = 1
BULK_CACHE_MAX_AGE_DAYS = 365


# MTGO bridge and background fetch timing
MTGO_BRIDGE_USERNAME_TIMEOUT_SECONDS = 2.0
MTGO_BRIDGE_SHUTDOWN_TIMEOUT_SECONDS = 10.0
MTGO_STATUS_POLL_SECONDS = 30
MTGO_STATUS_MAX_FAILURES = 10

MTGO_BACKGROUND_FETCH_DAYS = 7
MTGO_BACKGROUND_FETCH_DELAY_SECONDS = 2.0
MTGO_BACKGROUND_FETCH_SLEEP_STEP_SECONDS = 10
MTGO_BACKGROUND_FETCH_SLEEP_STEPS = 360

# Collection bridge fetch timing
COLLECTION_BRIDGE_TIMEOUT_SECONDS = 60.0

# External HTTP request timeouts
MTGGOLDFISH_REQUEST_TIMEOUT_SECONDS = 30
MTGO_DECKLISTS_REQUEST_TIMEOUT_SECONDS = 30
OPPONENT_TRACKER_REQUEST_TIMEOUT_SECONDS = 30

# Opponent tracker timers
OPPONENT_TRACKER_CACHE_TTL_SECONDS = 60 * 30
OPPONENT_TRACKER_POLL_INTERVAL_MS = 2000

# MTGGoldfish cache ages
MTGGOLDFISH_STALE_CACHE_DAYS = 7
MTGGOLDFISH_STALE_CACHE_SECONDS = ONE_DAY_SECONDS * MTGGOLDFISH_STALE_CACHE_DAYS

BRIDGE_PROCESS_TERMINATE_TIMEOUT_SECONDS = 2

# SQLite cache settings
SQLITE_CONNECTION_TIMEOUT_SECONDS = 30.0
SQLITE_BUSY_TIMEOUT_MS = 30000

# Card data download timing
ATOMIC_DATA_HEAD_TIMEOUT_SECONDS = 60
ATOMIC_DATA_DOWNLOAD_TIMEOUT_SECONDS = 300
