"""Card image display sizing and animation constants."""

CARD_IMAGE_DISPLAY_WIDTH = 260
CARD_IMAGE_DISPLAY_HEIGHT = 360
CARD_IMAGE_CORNER_RADIUS = 12
CARD_IMAGE_FLIP_ICON_SIZE = 32
CARD_IMAGE_FLIP_ICON_MARGIN = 10
CARD_IMAGE_ANIMATION_INTERVAL_MS = 16
CARD_IMAGE_ANIMATION_ALPHA_STEP = 0.15
CARD_IMAGE_PLACEHOLDER_INSET = 5
CARD_IMAGE_FLIP_ICON_TEXT_SCALE = 0.65
CARD_IMAGE_NAV_BUTTON_SIZE = (38, 30)
CARD_IMAGE_PRINTING_LABEL_MIN_WIDTH = 80
CARD_IMAGE_TEXT_MIN_HEIGHT = 120
CARD_IMAGE_COST_MIN_HEIGHT = 36
