"""Timer alert UI constants."""

TIMER_ALERT_FRAME_SIZE = (420, 400)
TIMER_ALERT_THRESHOLD_INPUT_SIZE = (80, -1)
TIMER_ALERT_REMOVE_BUTTON_SIZE = (30, -1)
TIMER_ALERT_STATUS_MIN_HEIGHT = 80
TIMER_ALERT_CHALLENGE_WRAP_WIDTH = 340
TIMER_ALERT_SCROLL_RATE_Y = 20

TIMER_ALERT_WATCH_INTERVAL_MS = 750
TIMER_ALERT_POLL_INTERVAL_MS = 1000
TIMER_ALERT_REPEAT_INTERVAL_DEFAULT_MS = 30000
TIMER_ALERT_REPEAT_INTERVAL_DEFAULT_SECONDS = 30

TIMER_ALERT_POLL_INTERVAL_MIN_MS = 250
TIMER_ALERT_POLL_INTERVAL_MAX_MS = 5000
TIMER_ALERT_REPEAT_INTERVAL_MIN_SECONDS = 5
TIMER_ALERT_REPEAT_INTERVAL_MAX_SECONDS = 300

TIMER_ALERT_DEFAULT_THRESHOLD_VALUE = "05:00"
