"""Window sizing constants for auxiliary frames."""

OPPONENT_TRACKER_FRAME_SIZE = (360, 180)
OPPONENT_TRACKER_LABEL_WRAP_WIDTH = 320
OPPONENT_TRACKER_SECTION_PADDING = 6
OPPONENT_TRACKER_SPACER_HEIGHT = 4
