"""Window sizing constants for auxiliary frames."""

OPPONENT_TRACKER_FRAME_SIZE = (400, 200)
OPPONENT_TRACKER_LABEL_WRAP_WIDTH = 320
OPPONENT_TRACKER_SECTION_PADDING = 6
OPPONENT_TRACKER_SPACER_HEIGHT = 4

# Sideboard Guide — Import Options dialog
GUIDE_IMPORT_OPTIONS_DIALOG_WIDTH = 400
GUIDE_IMPORT_OPTIONS_DIALOG_HEIGHT = 150
